# Generated by Django 5.2.8 on 2025-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="Заблокирован"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="Менеджер"),
        ),
    ]
