# Generated by Django 5.2.8 on 2025-11-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_is_blocked_customuser_is_manager"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("view_user_list", "Может просматривать список пользователей"),
                    ("block_user", "Может блокировать пользователей"),
                ]
            },
        ),
    ]
