# Generated by Django 5.2.8 on 2025-11-14 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_mailing",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                (
                    "last_mailing",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "создана"),
                            ("started", "запущена"),
                            ("ended", "завершена"),
                        ],
                        default="created",
                        max_length=8,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sendmails",
                        to="mailing.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="sendmails",
                        to="mailing.client",
                        verbose_name="Получатели",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_attempt",
                    models.DateTimeField(verbose_name="Дата и время попытки отправки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "успешно"), ("failed", "не успешно")],
                        max_length=8,
                        verbose_name="Статус",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Ответ почтового сервиса")),
                (
                    "sendmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mailing.sendmail",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
        ),
    ]
