# Generated by Django 5.2.8 on 2025-11-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_client_owner_sendmail_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    ("view_all_clients", "Может просматривать всех клиентов")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="sendmail",
            options={
                "permissions": [
                    ("view_all_sendmails", "Может просматривать все рассылки"),
                    ("disable_sendmail", "Может отключать рассылки"),
                ]
            },
        ),
    ]
